### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by telefonosuci** [apuigsech/emv-framework#5]
Running the script from cmd I got the following error:

C:\Users\enrico\git\emv-framework>python emv.py

Traceback (most recent call last):
  File "emv.py", line 15, in <module>
    from tlv import *
  File "C:\Users\enrico\git\emv-framework\tlv.py", line 109
    print '%s%.2x [%.2x] - %s' % (deep_str, self.code, self.size, self.name)
                             ^
SyntaxError: invalid syntax

**Comment by apuigsech** [comment]
This is related to the python version. My code is old code for python2, and I guess you are using python3.
